// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Newtomsoft.EntityFramework.Tests.DbContexts;

namespace Newtomsoft.EntityFramework.Tests.Migrations
{
    [DbContext(typeof(GoodDbContext_Development_))]
    partial class GoodDbContext_Development_ModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Newtomsoft.EntityFramework.Tests.Models.CityModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AverageAnnualIncome")
                        .HasColumnType("INTEGER");

                    b.Property<float>("AverageHouseholdPersons")
                        .HasColumnType("REAL");

                    b.Property<int>("Census")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CensusDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CountryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("City");
                });

            modelBuilder.Entity("Newtomsoft.EntityFramework.Tests.Models.CountryModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDemocracy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Country");
                });

            modelBuilder.Entity("Newtomsoft.EntityFramework.Tests.Models.CityModel", b =>
                {
                    b.HasOne("Newtomsoft.EntityFramework.Tests.Models.CountryModel", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });
#pragma warning restore 612, 618
        }
    }
}
